### ISSUE TITLE
A signin database issue

### ISSUE THREAD

**Issue by ssstoyanov** [ssstoyanov/server#9]
Seems it isn't working right

In following code:
```
bool checkPassword(char *password, FILE *database){
    //pointer is already in the line with login

    char *string = (char *) calloc(STR_LEN_MAX, sizeof(char));
    if (!string) exit(EXIT_FAILURE);
    char *stringbuf = (char *) calloc(STR_LEN_MAX, sizeof(char));
    if (!stringbuf) exit(EXIT_FAILURE);

    //getting password
    fgets(string, STR_LEN_MAX, database);
    stringbuf = strtok(string, ":");
    stringbuf = strtok(NULL, ":");
    stringbuf[strlen(stringbuf) - 1] = '\0';

    if (!strcmp(password, stringbuf))
        return true;
    else
        return false;

}
```
On the following data
![image](https://user-images.githubusercontent.com/46551118/83453843-e2ae1b00-a463-11ea-8547-3c99440ceabe.png)
Login parsing error
![image](https://user-images.githubusercontent.com/46551118/83453820-d88c1c80-a463-11ea-91a7-d57530a2ffcb.png)
Password comparison is in progress, not match username and password
![image](https://user-images.githubusercontent.com/46551118/83453830-dcb83a00-a463-11ea-969b-5c74743aac07.png)

**Comment by jswark** [comment]
Fixed by the commit cd394ed
